### ISSUE TITLE
Unresolvable dependency on easyrdf

### ISSUE THREAD

**Issue by erikap** [tdt/streamingrdfmapper#10]
Hi,

composer.json includes a dependency on: "easyrdf/easyrdf": "dev-devel", but it seems the devel branch doesn't exist anymore in the easyrdf repos. Please indicate which version should be used now.

Thank you,
Erika

**Comment by coreation** [comment]
Hi @erikap I think using the 0.9.0 should do the trick. If they followed the semantic versioning correctly it shouldn't break anything. Thanks for logging the issue!
